### ISSUE TITLE
Link in README not working

### ISSUE THREAD

**Issue by DawidJanczak** [CyberSource/cybersource-rest-client-ruby#79]
The [CyberSource API Keys](https://prod.developer.cybersource.com/api/developer-guides/dita-gettingstarted/registration/createCertSharedKey.html) link is broken.

**Comment by rsachan8** [comment]
Hi @DawidJanczak,
You can use this link for the same. https://developer.cybersource.com/docs/cybs/en-us/payments/developer/all/rest/payments/authentication.html 
We will update the README in the next release.
